{% set name = "zocalo-dls" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/zocalo_dls-{{ version }}.tar.gz
  sha256: 10b07792c0c16a00fac09ab9d516d5de4d4df06370a5d8415c7949260d21fa95

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
  run:
    - ispyb
    - procrunner
    - python >=3.6
    - setuptools
    - zocalo

test:
  imports:
    - zocalo_dls
    - zocalo_dls.service
    - zocalo_dls.wrapper
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/DiamondLightSource/python-zocalo-dls
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Standard components for automated data processing with Zocalo at Diamond Light Source
  doc_url: https://python-zocalo-dls.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - anthchirp
    - ndevenish
    - rjgildea
